Refactor: Proyect structure and enviroment.
pye-community/pye-community-bot pull request #13
Opened 2023-10-03 00:08 UTC by Chere3

- [ ] Change to `pnpm` for speed purposes.
- [ ] Change the config handling (because in some parts the part is not respected the config files).
- [ ]  Change file names to camelCase (since the name of the events uses this one).
- [ ] Change proyect structure (dir files)
- [ ] Add strict rules to the linter (eslint) to improve the contribution.
- [ ] Add github checkouts to find a better contribution environment.
- [ ] Add husky.

2023-10-03 14:50 UTC, Arkirion commented on src/config.ts
> +    channels: {
nit: Add TODO to change it, since this bot should be agnostic and not have any server configuration

2023-10-03 14:50 UTC, Arkirion commented on README.md
> +    yarn start       # if you use yarn
if we are not implementing yarn or npm then delete them from the readme

2023-10-03 14:50 UTC, Arkirion commented on src/events/handlers/nsfwFilter.ts
> +        const reportChannel = await client.channels.fetch(config.channels.reportes_channel);
cool, maybe this fix current issue.

2023-10-03 14:50 UTC, Arkirion commented on src/modules/bot/eventsLoader.ts
> +
nit: I dont know why left a extra line here, would prefer it closer to the function

2023-10-03 14:55 UTC, Chere3 commented on src/config.ts
> +    channels: {
✅ Added!

2023-10-03 14:58 UTC, Chere3 commented on README.md
> +    yarn start       # if you use yarn
Removed.👍🏼

2023-10-03 14:59 UTC, Chere3 commented on src/events/handlers/nsfwFilter.ts
> +        const reportChannel = await client.channels.fetch(config.channels.reportes_channel);
Yep, this was because the channel was not in the cache of the bot, because many times the cache of the channels is not taken until a certain event is detected in the channel. As messages.

2023-10-03 15:00 UTC, Chere3 commented on src/modules/bot/eventsLoader.ts
> +
👍🏼Resolved.

2023-10-03 15:03 UTC, Chere3 commented on src/modules/bot/eventsLoader.ts
> +    console.log(eventsPath);
Nah, it's not necessary, it's a `console.log` that escaped me to diagnose an error I had.

2023-10-03 15:53 UTC, Chere3 commented
@Alucherdi

2023-10-04 01:54 UTC, Chere3 commented
@Alucherdi hello

2023-10-04 01:59 UTC, romancitodev reviewed
Very gud!

2023-10-04 02:10 UTC, Alucherdi requested changes
Mmmm

2023-10-04 02:10 UTC, Alucherdi commented on src/config.ts
> +        retos_channels: ['1141493769699606528'],
bruh

2023-10-04 02:10 UTC, Alucherdi commented on src/index.ts
> +loadEvents(client).catch((err) => {}); client.login(config.bot.DISCORD_TOKEN).catch((err) => {});
Menos legibilidad

2023-10-04 02:10 UTC, Alucherdi commented on .prettierrc.js
> +    tabWidth: 4,
tabWidth a 2

2023-10-04 02:10 UTC, Alucherdi commented on src/commands/ping.ts
> +export const data = new SlashCommandBuilder().setName('ping').setDescription('replies with pong');
No

2023-10-04 02:10 UTC, Alucherdi commented on src/events/handlers/nsfwFilter.ts
> +    .then((r) => (model = r))
Catch bien, pero no mames

2023-10-04 02:10 UTC, Alucherdi commented on src/events/handlers/nsfwFilter.ts
> +        if (['Porn', 'Sexy'].includes(prediction[0].className)) {
Agregar matches en props

2023-10-04 02:10 UTC, Alucherdi commented on src/modules/bot/eventsLoader.ts
> +    const eventsFiles = readdirSync(`${eventsPath}`).filter((file) => file.match(/\.(ts|js)$/));
Dejar bl

2023-10-04 02:17 UTC, Chere3 commented on .vscode/settings.json
> +    }
vscode es hermoso we. No es necesario remover nada, naco.

2023-10-04 02:17 UTC, Chere3 commented on .prettierrc.js
> +    tabWidth: 4,
Cambiado el tabwidth

2023-10-04 02:17 UTC, Alucherdi commented on .vscode/settings.json
> +    }
vete mucho a la verga padrino

2023-10-04 02:17 UTC, Arkirion commented on src/commands/ping.ts
> +export const data = new SlashCommandBuilder().setName('ping').setDescription('replies with pong');
I agree

2023-10-04 02:29 UTC, Alucherdi approved these changes

2023-10-04 02:31 UTC, Arkirion approved these changes

2023-10-04 02:33 UTC, merged