horoscope command
pye-community/pye-community-bot pull request #14
Opened 2023-10-04 07:02 UTC by elmagoasensio

Con estrellas brillantes y un código sin error,
Este pull-request, aceptado será con honor.
Que los astros se alineen y el merge se haga realidad,
Que así sea, así sea, en esta noche estelar.

2023-10-04 19:52 UTC, Chere3 requested changes
Certain parts of the code or techniques are unnecessary. 👇🏼

2023-10-04 19:52 UTC, Chere3 commented on src/commands/horoscopo.ts
> +    map.set("aries", 1);
Avoid the use of Map, use objects instead.

2023-10-04 19:52 UTC, Chere3 commented on src/commands/horoscopo.ts
> +            {name: "tauro", value: "tauro"},
You could use only 1 object to define command options, and options to get API data.

Like this:
```ts
let signData = {
    "aries": { id: 1, emoji: "♈️" },
    "tauro": { id: 2, emoji: "♉️" },
    "geminis": { id: 3, emoji: "♊️" },
    "cancer": { id: 4, emoji: "♋️" },
    "leo": { id: 5, emoji: "♌️" },
    "virgo": { id: 6, emoji: "♍️" },
    "libra": { id: 7, emoji: "♎️" },
    "escorpion": { id: 8, emoji: "♏️" },
    "sagitario": { id: 9, emoji: "♐️" },
    "capricornio": { id: 10, emoji: "♑️" },
    "acuario": { id: 11, emoji: "♒️" },
    "picis": { id: 12, emoji: "♓️" }
};
```

Although you can still avoid putting the ID, since it can be extracted by the value of the array itself.

2023-10-04 19:52 UTC, Chere3 commented on src/commands/horoscopo.ts
> +        axios.get('https://www.misabueso.com/esoterica/horoscopo/?zod=' + signId)
Avoid using axios. Use fetch API instead.

2023-10-04 19:52 UTC, Chere3 commented on src/commands/horoscopo.ts
> +    if (interaction.user.id === "401845716991082496") {//romandev. https://discord.com/channels/768278151435386900/1055594415286140979/1154141982948610149
Unnecessary code. Avoid discriminating against users under commands.

2023-10-04 21:54 UTC, romancitodev commented on src/commands/horoscopo.ts
> +    if (interaction.user.id === "401845716991082496") {//romandev. https://discord.com/channels/768278151435386900/1055594415286140979/1154141982948610149
Why is my ID there? Lmao

2023-10-04 21:55 UTC, romancitodev commented
I do not approve this merge because i think it's an useless command.

You can use NotSoBot instead.

2023-10-05 03:08 UTC, Chere3 commented
Joke PR.

2023-10-05 03:08 UTC, closed without merging