Feature/share threads
pye-community/pye-community-bot pull request #38
Opened 2023-10-22 03:34 UTC by Arkirion

![image](https://github.com/pye-community/pye-community-bot/assets/67301108/b2e551c6-6c18-44b5-beb5-d359c79930d2)

2023-10-22 03:38 UTC, Chere3 requested changes

2023-10-22 03:38 UTC, Chere3 commented on src/config.ts
> +      '1122399272499941426', // dart
Very bad practice, use the parentChannel instead to fetch all the channels in category.
https://old.discordjs.dev/#/docs/discord.js/main/class/ThreadChannel?scrollTo=parent

2023-10-22 03:45 UTC, Arkirion commented on src/config.ts
> +      '1122399272499941426', // dart
We are not adding all forums

2023-10-22 03:46 UTC, Arkirion commented on src/config.ts
> +      '1122399272499941426', // dart
also some forums are on different categories

2023-10-22 03:46 UTC, Arkirion commented on src/config.ts
> +      '1122399272499941426', // dart
we need storage in order to avoid this config =)

2023-10-22 03:48 UTC, Chere3 commented on src/config.ts
> +      '1122399272499941426', // dart
In that case it is better to create two properties, one of the categories to be obtained, and one of the channels to be ignored within those categories

```json
{
   forumTargets: ["category1", "category2"],
   ignoredChannels: ["channel1", "channel2"]
}

2023-10-22 03:49 UTC, Chere3 commented on src/config.ts
> +      '1122399272499941426', // dart
And you can leave a channel property, for channels that are outside the categories, such as the math channel

2023-10-22 19:27 UTC, Arkirion commented on src/config.ts
> +      '1122399272499941426', // dart
as I said on Discord, I understand your approach, however ( ignoring that we are using a file to set this config ) is more easier just add or remove ids, Im against these conditions that are not that clear like just add or remove things, even if it mean a lot of ids

2023-10-22 21:18 UTC, Chere3 requested changes

2023-10-22 21:18 UTC, Chere3 commented on src/config.ts
> +        id: '807385882868580392'
follow the format of the channels ids.
Property id is unnecesary.

```json
"outputChannel": {
  "chat_programadores": "807385882868580392"
 }

2023-10-23 04:25 UTC, Chere3 approved these changes

2023-10-23 05:44 UTC, merged