Feature/threads managment
pye-community/pye-community-bot pull request #40
Opened 2023-10-22 16:07 UTC by romancitodev

🎯 This PR introduces an important feature to manage help threads effectively (see #10).

The primary goal of this PR is to add the `/solucionado` command, which allows the original poster to tag the thread as 'Solucionado' when they have resolved their issue.

2023-10-22 16:08 UTC, Chere3 requested changes

2023-10-22 16:08 UTC, Chere3 commented on src/commands/threads/solution.ts
> +/* eslint-disable @typescript-eslint/restrict-template-expressions */
Remove.

2023-10-22 16:12 UTC, romancitodev commented on src/commands/threads/solution.ts
> +/* eslint-disable @typescript-eslint/restrict-template-expressions */
Done

2023-11-04 03:57 UTC, Arkirion commented
user say that we wont do it so we are closing this PR

2023-11-04 03:57 UTC, closed without merging